-- Calendar: the four Timewalking weeks, each under its own name; their dates are written by the server at every startup (Timewalking.*).
ALTER TABLE `custom_calendar_event`
  MODIFY `Description` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT 'announcement body, in English',
  MODIFY `DescriptionLocalized` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT 'announcement body, in the server locale';

DELETE FROM `custom_calendar_event` WHERE `HolidayID` IN (559, 562, 587, 643);
INSERT INTO `custom_calendar_event` (`HolidayID`, `HolidayNameID`, `HolidayDescriptionID`, `Name`, `NameLocalized`, `Description`, `DescriptionLocalized`, `StartDate`, `EndDate`, `DurationDays`, `RepeatDays`, `Texture1`, `Texture2`, `Texture3`, `Enabled`, `GameEventID`, `Notes`) VALUES
(559, 196, 222, 'Timewalking: The Burning Crusade', 'Marcheurs du temps : The Burning Crusade', 'While this event is active, players level 71 or higher may access a special Timewalking Dungeon Finder queue, which scales players and their items down to revisit past dungeons from The Burning Crusade expansion. While Timewalking, bosses will yield loot appropriate for a player''s natural level.', 'Pendant cet évènement, les personnages-joueurs de niveau 71 ou supérieur peuvent entrer en file d’attente d’un donjon des Marcheurs du temps, ce qui leur fera remonter le temps ainsi qu’à leurs objets pour revisiter des donjons de l’extension The Burning Crusade. Le butin des boss est adapté au niveau d’origine du personnage-joueur.', NULL, NULL, 7, 0, 1129674, 1129673, 1129672, 0, 0, 'Dates written at startup by Timewalking::PrepareCalendar'),
(562, 197, 220, 'Timewalking: Wrath of the Lich King', 'Marcheurs du temps : Wrath of the Lich King', 'While this event is active, players level 81 or higher may access a special Timewalking Dungeon Finder queue, which scales players and their items down to revisit past dungeons from the Wrath of the Lich King expansion. While Timewalking, bosses will yield loot appropriate for a player''s natural level.', 'Pendant toute la durée de cet évènement, les personnages-joueurs de niveau 81 ou supérieur peuvent se placer en file d’attente pour un donjon des Marcheurs du temps, ce qui leur fera remonter le temps, ainsi qu’à leurs objets, pour revisiter de précédents donjons de l’extension Wrath of the Lich King. Durant cette période, les boss rapportent un butin adapté au niveau véritable du personnage-joueur.', NULL, NULL, 7, 0, 1129686, 1129685, 1129684, 0, 0, 'Dates written at startup by Timewalking::PrepareCalendar'),
(587, 198, 224, 'Timewalking: Cataclysm', 'Marcheurs du temps : Cataclysm', 'While this event is active, players level 86 or higher may access a special Timewalking Dungeon Finder queue, which scales players and their items down to revisit past dungeons from the Cataclysm expansion. While Timewalking, bosses will yield loot appropriate for a player''s natural level.', 'Pendant toute la durée de cet évènement, les personnages-joueurs de niveau 86 ou supérieur peuvent se placer en file d’attente pour un donjon des Marcheurs du temps, ce qui leur fera remonter le temps ainsi qu’à leurs objets pour revisiter de précédents donjons de l’extension Cataclysm. Durant cette période, les boss rapportent un butin adapté au niveau d’origine du personnage-joueur.', NULL, NULL, 7, 0, 1304688, 1304687, 1304686, 0, 0, 'Dates written at startup by Timewalking::PrepareCalendar'),
(643, 199, 237, 'Timewalking: Mists of Pandaria', 'Marcheurs du temps : Mists of Pandaria', 'While this event is active, players level 91 or higher may access a special Timewalking Dungeon Finder queue, which scales players and their items down to revisit past dungeons from the Mists of Pandaria expansion. While Timewalking, bosses will yield loot appropriate for a player''s natural level.', 'Pendant toute la durée de cet évènement, les personnages-joueurs de niveau 91 ou supérieur peuvent se placer en file d’attente pour un donjon des Marcheurs du temps, ce qui leur fera remonter le temps, ainsi qu’à leurs objets, pour revisiter de précédents donjons de l’extension Mist of Pandaria. Durant cette période, les boss rapportent un butin adapté au niveau véritable du personnage-joueur.', NULL, NULL, 7, 0, 1530590, 1530589, 1530588, 0, 0, 'Dates written at startup by Timewalking::PrepareCalendar');
